title = 'Docura'
baseURL = 'https://docura.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

enableGitInfo = true

markup.highlight.noClasses = false

[services]
[services.googleAnalytics]
ID = 'G-XXXXXXXXXX'