description = 'A modular Hugo theme to build your next documentation site'

currentYear = 2023
# projectStartYear = 2020

facebookURL = 'https://facebook.com/'
twitterURL = 'https://www.twitter.com/'
githubURL = 'https://github.com/'
youtubeURL = 'https://www.youtube.com/'

githubRepo = 'your/repo'

buyMeACoffee = ''
githubSponsor = ''
#googleAdSense = 'ca-pub-xxxxxxxxxxxxxxxx'

[author]
name= 'Your Name'
URL = 'https://your-site.com/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = ''
indexName = ''
apiKey = ''

#[[githubRepos]]
#name = 'Website'
#repo = 'docura/site'
#icon = "<i class='icon icon-book'></i>"
#description = 'The repository of the website.'
#
#[[githubRepos]]
#name = 'Code'
#repo = 'docura/docura'
#icon = "<i class='icon icon-theme'></i>"
#description = 'The repository of the theme.'
