description = 'A modular Hugo theme to build your next documentation site'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

facebookURL = 'https://facebook.com/HugoDocura'
twitterURL = 'https://www.twitter.com/'
githubURL = 'https://github.com/docura/site'
youtubeURL = 'https://www.youtube.com/'

githubRepo = 'docura/site'
githubSponsorURL = 'https://github.com/sponsors/dumindu'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/dumindu'

hugoURL = 'https://gohugo.io/'
docuraURL = 'https://docura.github.io/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = 'docura'
indexName = 'docura'
apiKey = ''
